name: udacity_env
channels:
  - defaults
dependencies:
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1h=haf1e3a3_0
  - pip=20.2.4=py39hecd8cb5_0
  - python=3.9.0=h88f2d9e_1
  - readline=8.0=h1de35cc_0
  - setuptools=50.3.1=py39hecd8cb5_1
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - tzdata=2020d=h14c3975_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/sandrinevuachet/anaconda3/envs/udacity_env
